"""add-allegations

Revision ID: 171ee9412815
Revises: 8fc4d110de2c
Create Date: 2023-08-05 00:14:32.513077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171ee9412815'
down_revision = '8fc4d110de2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allegations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_updated', sa.DateTime(), nullable=True),
    sa.Column('allegation', sa.String(length=255), nullable=True),
    sa.Column('disposition', sa.String(length=255), nullable=True),
    sa.Column('discipline', sa.String(length=255), nullable=True),
    sa.Column('finding', sa.String(length=255), nullable=True),
    sa.Column('officer_name', sa.String(length=255), nullable=True),
    sa.Column('star_no', sa.String(length=120), nullable=True),
    sa.Column('incident_type', sa.String(length=255), nullable=True),
    sa.Column('case', sa.String(length=255), nullable=True),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('incident_id', sa.Integer(), nullable=False),
    sa.Column('officer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ),
    sa.ForeignKeyConstraint(['officer_id'], ['officers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('allegations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_allegations_date_updated'), ['date_updated'], unique=False)
        batch_op.create_index(batch_op.f('ix_allegations_star_no'), ['star_no'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('allegations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_allegations_star_no'))
        batch_op.drop_index(batch_op.f('ix_allegations_date_updated'))

    op.drop_table('allegations')
    # ### end Alembic commands ###
