"""empty message

Revision ID: 3eb46cc6be4d
Revises: 5865f488470c
Create Date: 2024-10-25 07:21:26.375413

"""

import sqlalchemy as sa
from alembic import op


revision = "3eb46cc6be4d"
down_revision = "5865f488470c"


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allegations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("incident_id", sa.Integer(), nullable=True),
        sa.Column("officer_id", sa.Integer(), nullable=True),
        sa.Column("disposition", sa.Text(), nullable=False),
        sa.Column("discipline", sa.Text(), nullable=True),
        sa.Column("type", sa.Text(), nullable=False),
        sa.Column("finding", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("created_by", sa.Integer(), nullable=True),
        sa.Column("last_updated_by", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["created_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["incident_id"], ["incidents.id"], name="allegations_incident_id_fkey"
        ),
        sa.ForeignKeyConstraint(["last_updated_by"], ["users.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(
            ["officer_id"], ["officers.id"], name="allegations_officer_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("allegations")
    # ### end Alembic commands ###
