"""Add date_created and date_updated columns to officers table

Revision ID: aaedadb06bf0
Revises: cd39b33b5360
Create Date: 2022-10-02 10:01:27.683640

"""
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision = "aaedadb06bf0"
down_revision = "cd39b33b5360"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("officers", sa.Column("date_created", sa.DateTime(), nullable=True))
    op.add_column("officers", sa.Column("date_updated", sa.DateTime(), nullable=True))

    op.execute(
        """
        update officers
        set date_created='2021-12-28',
            date_updated='2021-12-28';
        """
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("officers", "date_updated")
    op.drop_column("officers", "date_created")
    # ### end Alembic commands ###
